# Use an official Python runtime as a parent image
FROM python:3.8

# Set environment variables for PostgreSQL connection
ENV POSTGRES_DB=mydb
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=!Password1999
ENV POSTGRES_HOST=postgres

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app/

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Expose port 8000 for the Django application
EXPOSE 8000

# Start the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
